decoration {
	dim_special = 0.3
	active_opacity = 0.9
	inactive_opacity = 0.9
	fullscreen_opacity = 0.9
	# active_opacity = 1
	# inactive_opacity = 1
	# fullscreen_opacity = 1
    rounding = 20

    shadow {
        enabled = false
        # range = 4
        # render_power = 3
        # color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
		xray = false
        size = 7
        vibrancy_darkness = 3.0
        passes = 4
        vibrancy = 0.1796
    }

	layerrule = blur,waybar
	# layerrule = blur,swaync-control-center
	# layerrule = blur,swaync-notification-window
	# layerrule = ignorealpha 0.4, swaync-control-center
	# layerrule = ignorealpha 0.4, swaync-notification-window

	layerrule = blur, notifications
	layerrule = ignorealpha 0.5, notifications

	layerrule = blur, wofi
	layerrule = blur, rofi
	layerrule = ignorealpha 0.0, rofi
	# layerrule = ignorealpha 0.5, rofi

	# layerrule = active_opacity 0.95, vivaldi

windowrulev2 = float, class:^(sidebar-box)$
windowrulev2 = nofocus, class:^(sidebar-box)$
windowrulev2 = stayfocused, class:^(sidebar-box)$
layerrule = blur, class:sidebar-box

layerrule=ignorezero, class:sidebar-box
layerrule=blur, overlay
layerrule = ignorealpha 0.5, class:sidebar-box

	layerrule=ignorezero, gtk-layer-shell
	layerrule=ignorezero, swww-daemon
	layerrule=blur, swww-daemon

	blurls=sidebar-window

layerrule=ignorezero, sidebar-window

layerrule = blur,^(eww-blur)$
layerrule = ignorealpha 0 0,^(eww-blur)$
layerrule = blur,^(gtk-layer-shell)$
}

