decoration {
	dim_special = 0.3
	active_opacity = 0.9
	inactive_opacity = 0.85
	fullscreen_opacity = 1
	# active_opacity = 1
	# inactive_opacity = 1
	# fullscreen_opacity = 1
    rounding = 20

    shadow {
        enabled = false
        # range = 4
        # render_power = 3
        # color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
		xray = false
        size = 7
        vibrancy_darkness = 3.0
        passes = 4
        vibrancy = 0.1796
    }

}

