#!/bin/bash

export DISPLAY=$DISPLAY
export XAUTHORITY=$XAUTHORITY
export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
export DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS
export HOME=$HOME
export XDG_CONFIG_HOME=$XDG_CONFIG_HOME

pkexec env \
    DISPLAY=$DISPLAY \
    XAUTHORITY=$XAUTHORITY \
    WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
    DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
    HOME=$HOME \
    XDG_CONFIG_HOME=$XDG_CONFIG_HOME \
    /usr/bin/hiddify

