exec-once = ~/.config/waybar/launch-waybar.sh
# exec-once = ~/.config/hyprpanel/launch-hyprpanel.sh
# exec-once = eww daemon &
# exec-once = dunst
exec-once = swaync &
exec-once = hyprpaper &
exec-once = keepassxc
exec-once = hiddify
exec-once = udiskie
exec-once = hypridle

# NOTE: I disabled it because hyprpanel starts it by itself
# exec-once = mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
# exec = hyprshade on blue-light-filter


# NOTE: This is wallpaper daemon, but i use hyprpaper, so
# i probably do not need it. Maybe i will try swww later
exec-once = swww-daemon --format xrgb


# Мои скрипты
exec = ~/.config/hypr/scripts/hyprshade.py --restore
exec = ~/.config/hypr/scripts/set-wallpaper-swww.sh --load

exec = ~/.config/scripts/check-btc-seeds.py 5


# These ones from hyprluna



# this is terminal, i dont use it
# exec-once = foot --server 

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --all
exec-once = hyprpm reload
# Cursor
# exec-once = hyprctl setcursor Bibata-Modern-Ice 24
# exec = hyprctl setcursor Bibata-Modern-DarkRed 20
# exec = hyprctl setcursor GoogleDot-Black 20
exec = hyprctl setcursor Bibata-Modern-Classic 20

# Force Geist in Hyprland
exec-once = gsettings set org.gnome.desktop.interface font-name 'Geist'
exec-once = gsettings set org.gnome.desktop.interface document-font-name 'Geist'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'Geist Mono'
exec-once = gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Geist'
# set dark theme

# NOTE: i will do it via ng look or something
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# Audio
exec-once = easyeffects --gapplication-service
# Clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store



# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
