decoration {
    rounding = 10
    blur {
        enabled = true
        size = 2
        passes = 4
        vibrancy = 0.1696
    }
    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

	layerrule = blur,waybar
	layerrule = blur,layer:0
	layerrule = blur,namespace:bar-1
	layerrule = blur, bar-0
	layerrule = blur, bar
	layerrule = ignorealpha 0.01, bar-1
	# layerrule = blur,swaync-control-center
	# layerrule = blur,swaync-notification-window
	# layerrule = ignorealpha 0.4, swaync-control-center
	# layerrule = ignorealpha 0.4, swaync-notification-window

	layerrule = blur, notifications
	layerrule = ignorealpha 0.5, notifications

	layerrule = blur, wofi
	layerrule = blur, rofi
	layerrule = ignorealpha 0.0, rofi
	# layerrule = ignorealpha 0.5, rofi

	windowrule = opacity 0.99 0.99,class:Vivaldi-stable
	# windowrule = namespace:bar-0,blur

# Apply blur effect to the bar layers (bar-0 and bar-1)
# Try targeting bars on layer 2 using namespace
	windowrule=namespace:bar-0,layer:2,blur:12
	windowrule=namespace:bar-1,layer:2,blur:12
}

