windowrule {
	name = blueman
	match:class = blueman-manager

	float = on
	size = 800 500
	center = on
}

windowrule {
	name = keepassxcunlock
	match:title = Unlock Database - KeePassXC

	float = on
	center = on
	size = 800 500
}


windowrule {
	name = floatapps
	match:title = Выбор файлов

	float = on
	center = on
	size = 800 500
}


windowrule {
	name = floatTelegramMedia
	match:title = Просмотр медиа

	fullscreen = on

	# float = on
	# center = on
}


windowrule {
	name = floatapps
	match:title = Сохранение изображения

	float = on
	center = on
	size = 800 500
}


windowrule {
	name = floatapps
	match:title = KeePassXC - Browser Access Request

	float = on
	center = on
	size = 800 500
}




windowrule {
	name = floatapps
	match:title = Firefox - Choose User Profile

	float = on
	center = on
	size = 800 500
}


layerrule {
	name = bluron2
	match:class = logout_dialog
	blur = on
}


layerrule {
	name = bluron
	match:class = rofi
	blur = on
	ignore_alpha = 0.5
}

layerrule {
	name = bluron1
	match:class = swaync-control-center
	blur = on
	ignore_alpha = 0.05
}

layerrule {
	name = bluron1
	match:class = swaync-notification-window
	blur = on
	ignore_alpha = 0.4
}



# layerrule = unset, rofi
# layerrule = ignorezero, rofi


# layerrule = ignorealpha 0.5, swaync-control-center
# layerrule = ignorealpha 0.5, swaync-notification-window

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*
# windowrule = match:class .*, suppressevent maximize

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# windowrulev2 = workspace 10 silent, class:^(keepassxc)$
# windowrulev2 = workspace 10 silent, class:^([Hh]iddify)$

windowrule = move 10 silent, match:class org.keepassxc.KeePassXC
windowrule = move 10 silent, match:class ^([Hh]iddify)$

windowrule {
	name = move
	# match:class = ^([Kk]ee[Pp]ass[Xx][Cc])$
	# match:class = org.keepassxc.KeePassXC
	match:class = ^([Hh]iddify)$
	workspace = 10 silent
}


windowrule {
	name = move
	# match:class = ^([Kk]ee[Pp]ass[Xx][Cc])$
	match:class = org.keepassxc.KeePassXC
	# match:class = ^([Hh]iddify)$
	workspace = 10 silent
}


layerrule {
	name = firefo4
	match:class = firefox
	ignore_alpha = 0.1
}

layerrule {
	name = waybar
	match:class = waybar
	ignore_alpha = 1
}



	# layerrule = blur,waybar

	# layerrule = blur,swaync-control-center
	# layerrule = blur,swaync-notification-window
	# layerrule = ignorealpha 0.4, swaync-control-center
	# layerrule = ignorealpha 0.4, swaync-notification-window

	# layerrule = blur, notifications
	# layerrule = ignorealpha 0.5, notifications

	# layerrule = blur, wofi
	# layerrule = blur, rofi
	# layerrule = ignorealpha 0.0, rofi
	# layerrule = ignorealpha 0.5, rofi

	# layerrule = active_opacity 0.95, vivaldi

# windowrulev2 = float, class:^(sidebar-box)$
# windowrulev2 = nofocus, class:^(sidebar-box)$
# windowrulev2 = stayfocused, class:^(sidebar-box)$
# layerrule = blur, class:sidebar-box

# layerrule=ignorezero, class:sidebar-box
# layerrule=blur, overlay
# layerrule = ignorealpha 0.5, class:sidebar-box

	# layerrule=ignorezero, gtk-layer-shell
	# layerrule=ignorezero, swww-daemon
	# layerrule=blur, swww-daemon

	# blurls=sidebar-window

# layerrule=ignorezero, sidebar-window

# layerrule = blur,^(eww-blur)$
# layerrule = ignorealpha 0 0,^(eww-blur)$
# layerrule = blur,^(gtk-layer-shell)$
